### ISSUE TITLE
CocoaPods Compatability

### ISSUE THREAD

**Issue by jmyers0022** [dawnwallet/dawn-key-management#8]
Hello folks. I'm curious to know if you've had any thoughts or done any work to make this available via CocoaPods? We're trying to integrate this into a React Native project, which doesn't support Swift Package Manager at this time.

We've begun work to CocoaPod-ify it, but are running into issues, and wanted to make sure we aren't going down a path already traveled.

**Comment by sideround** [comment]
Hey @jmyers0022 - thank you for your interest on our key management repo! 

We don't have any plans to support CocoaPods in the near future. This repo was meant to be supported via SPM only, as the structure to support both could lead to structural changes. That said, we would be more than happy to review any PR that adds support for Cocoapods!
